### ISSUE TITLE
[Feature] - Pseudo realtime frequency sweep on HDAWG

### ISSUE THREAD

**Issue by GlaserN** [zhinst/laboneq#24]
On SHFSG devices a realtime frequency sweep can be used. On the HDAWG this behaviour can be achieved by individually sampling out the waveforms to play on the device. In order to increase compatibility between experiments using either HDAWG or SHFSG it would be great if one could also perform pseudo realtime sweeps on the HDAWG this way, at the cost of a higher waveform consumption.

**Comment by QuantumClemens** [comment]
Hi @GlaserN , 
Since 1.7, real-time frequency sweeps with hardware modulation are already possible on the HDAWG, see https://docs.zhinst.com/labone_q_user_manual/release_notes.html. 
From 2.0, released later this week, also real-time frequency sweeps with a software oscillator will be possible. I am assuming this is what you are referring to here?

**Comment by GlaserN** [comment]
Thanks for the update.
